name = "fly_template"
version = "1.0.0"
licences = ["MIT"]
description = "Template for deploying a Nakai app on Fly.io"
repository = { type = "github", user = "nakaixo", repo = "fly_template" }


[dependencies]
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
gleam_stdlib = ">= 0.36.0 and < 2.0.0"
mist = "~> 1.0"
nakai = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"
