name = "fly_template"
version = "1.0.0"
licences = ["MIT"]
description = "Template for deploying a Nakai app on Fly.io"
repository = { type = "github", user = "nakaibuild", repo = "fly_template" }


[dependencies]
gleam_elli = "~> 2.0"
gleam_http = "~> 3.1"
gleam_stdlib = "~> 0.25"
nakai = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.7"
