name = "fly_template"
version = "1.0.0"
licences = ["MIT"]
description = "Template for deploying a Nakai app on Fly.io"
repository = { type = "github", user = "nakaixo", repo = "fly_template" }


[dependencies]
gleam_elli = "~> 2.1"
gleam_http = "~> 3.4"
gleam_stdlib = "~> 0.30"
nakai = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 0.10"
