name = "fly_template"
version = "1.0.0"
# licences = ["0BSD"]
# description = "Template for deploying a Nakai app on Fly.io"
# repository = { type = "github", user = "nakaixo", repo = "fly_template" }


[dependencies]
gleam_erlang = "~> 0.31"
gleam_http = "~> 3.7"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
mist = "~> 3.0"
nakai = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 1.2"
